# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            ElasticSight
tagline:          'A Jekyll theme'
description:      'Custom analytics like a breeze'
url:              https://elasticsight.github.io
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0


